<?php
/**
 * @category   Shashank
 * @package    Shashank_Don
 * @author     shashank.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Shashank\Don\Block;

use Magento\Framework\View\Element\Template\Context;
use Shashank\Don\Model\DonFactory;
/**
 * Don List block
 */
class DonListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Don
     */
    protected $_don;
    public function __construct(
        Context $context,
        DonFactory $don
    ) {
        $this->_don = $don;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Shashank Don Module List Page'));
        
        if ($this->getDonCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'shashank.don.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getDonCollection()
            );
            $this->setChild('pager', $pager);
            $this->getDonCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getDonCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $don = $this->_don->create();
        $collection = $don->getCollection();
        $collection->addFieldToFilter('status','1');
        //$don->setOrder('don_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}