<?php
/**
 * @category   Shashank
 * @package    Shashank_Don
 * @author     shashank.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Shashank\Don\Block;

use Magento\Framework\View\Element\Template\Context;
use Shashank\Don\Model\DonFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Don View block
 */
class DonView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Don
     */
    protected $_don;
    public function __construct(
        Context $context,
        DonFactory $don,
        FilterProvider $filterProvider
    ) {
        $this->_don = $don;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Shashank Don Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $don = $this->_don->create();
        $singleData = $don->load($id);
        if($singleData->getDonId() && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}