<?php
/**
 * @category   Shashank
 * @package    Shashank_Don
 * @author     shashank.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Shashank\Don\Model\ResourceModel;

class Don extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('shashank_don', 'don_id');   //here "shashank_don" is table name and "don_id" is the primary key of custom table
    }
}